/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as ScanAlertRouteImport } from './routes/scan.alert'
import { Route as ReportDomainRouteImport } from './routes/report.$domain'
import { Route as ScanAlertIndexRouteImport } from './routes/scan.alert.index'
import { Route as ScanAlertDetailsRouteImport } from './routes/scan.alert.details'
import { Route as ScanAlertAlternativesRouteImport } from './routes/scan.alert.alternatives'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanRoute,
} as any)
const ScanAlertRoute = ScanAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => ScanRoute,
} as any)
const ReportDomainRoute = ReportDomainRouteImport.update({
  id: '/report/$domain',
  path: '/report/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanAlertIndexRoute = ScanAlertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanAlertRoute,
} as any)
const ScanAlertDetailsRoute = ScanAlertDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => ScanAlertRoute,
} as any)
const ScanAlertAlternativesRoute = ScanAlertAlternativesRouteImport.update({
  id: '/alternatives',
  path: '/alternatives',
  getParentRoute: () => ScanAlertRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/design': typeof DesignRoute
  '/environment': typeof EnvironmentRoute
  '/scan': typeof ScanRouteWithChildren
  '/report/$domain': typeof ReportDomainRoute
  '/scan/alert': typeof ScanAlertRouteWithChildren
  '/scan/': typeof ScanIndexRoute
  '/scan/alert/alternatives': typeof ScanAlertAlternativesRoute
  '/scan/alert/details': typeof ScanAlertDetailsRoute
  '/scan/alert/': typeof ScanAlertIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/design': typeof DesignRoute
  '/environment': typeof EnvironmentRoute
  '/report/$domain': typeof ReportDomainRoute
  '/scan': typeof ScanIndexRoute
  '/scan/alert/alternatives': typeof ScanAlertAlternativesRoute
  '/scan/alert/details': typeof ScanAlertDetailsRoute
  '/scan/alert': typeof ScanAlertIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/design': typeof DesignRoute
  '/environment': typeof EnvironmentRoute
  '/scan': typeof ScanRouteWithChildren
  '/report/$domain': typeof ReportDomainRoute
  '/scan/alert': typeof ScanAlertRouteWithChildren
  '/scan/': typeof ScanIndexRoute
  '/scan/alert/alternatives': typeof ScanAlertAlternativesRoute
  '/scan/alert/details': typeof ScanAlertDetailsRoute
  '/scan/alert/': typeof ScanAlertIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/chat'
    | '/design'
    | '/environment'
    | '/scan'
    | '/report/$domain'
    | '/scan/alert'
    | '/scan/'
    | '/scan/alert/alternatives'
    | '/scan/alert/details'
    | '/scan/alert/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/chat'
    | '/design'
    | '/environment'
    | '/report/$domain'
    | '/scan'
    | '/scan/alert/alternatives'
    | '/scan/alert/details'
    | '/scan/alert'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/chat'
    | '/design'
    | '/environment'
    | '/scan'
    | '/report/$domain'
    | '/scan/alert'
    | '/scan/'
    | '/scan/alert/alternatives'
    | '/scan/alert/details'
    | '/scan/alert/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ChatRoute: typeof ChatRoute
  DesignRoute: typeof DesignRoute
  EnvironmentRoute: typeof EnvironmentRoute
  ScanRoute: typeof ScanRouteWithChildren
  ReportDomainRoute: typeof ReportDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/alert': {
      id: '/scan/alert'
      path: '/alert'
      fullPath: '/scan/alert'
      preLoaderRoute: typeof ScanAlertRouteImport
      parentRoute: typeof ScanRoute
    }
    '/report/$domain': {
      id: '/report/$domain'
      path: '/report/$domain'
      fullPath: '/report/$domain'
      preLoaderRoute: typeof ReportDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/alert/': {
      id: '/scan/alert/'
      path: '/'
      fullPath: '/scan/alert/'
      preLoaderRoute: typeof ScanAlertIndexRouteImport
      parentRoute: typeof ScanAlertRoute
    }
    '/scan/alert/details': {
      id: '/scan/alert/details'
      path: '/details'
      fullPath: '/scan/alert/details'
      preLoaderRoute: typeof ScanAlertDetailsRouteImport
      parentRoute: typeof ScanAlertRoute
    }
    '/scan/alert/alternatives': {
      id: '/scan/alert/alternatives'
      path: '/alternatives'
      fullPath: '/scan/alert/alternatives'
      preLoaderRoute: typeof ScanAlertAlternativesRouteImport
      parentRoute: typeof ScanAlertRoute
    }
  }
}

interface ScanAlertRouteChildren {
  ScanAlertAlternativesRoute: typeof ScanAlertAlternativesRoute
  ScanAlertDetailsRoute: typeof ScanAlertDetailsRoute
  ScanAlertIndexRoute: typeof ScanAlertIndexRoute
}

const ScanAlertRouteChildren: ScanAlertRouteChildren = {
  ScanAlertAlternativesRoute: ScanAlertAlternativesRoute,
  ScanAlertDetailsRoute: ScanAlertDetailsRoute,
  ScanAlertIndexRoute: ScanAlertIndexRoute,
}

const ScanAlertRouteWithChildren = ScanAlertRoute._addFileChildren(
  ScanAlertRouteChildren,
)

interface ScanRouteChildren {
  ScanAlertRoute: typeof ScanAlertRouteWithChildren
  ScanIndexRoute: typeof ScanIndexRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanAlertRoute: ScanAlertRouteWithChildren,
  ScanIndexRoute: ScanIndexRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ChatRoute: ChatRoute,
  DesignRoute: DesignRoute,
  EnvironmentRoute: EnvironmentRoute,
  ScanRoute: ScanRouteWithChildren,
  ReportDomainRoute: ReportDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
